#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

for FILE in `git diff-index --name-status $against -- | cut -c3-` ; do
    # Check if the file contains 'fdescribe("'
    if grep -q -e '^ *fdescribe(\"' -e '^ *fcontext(\"' -e '^ *fit(\"' "$FILE"
    then
        echo $FILE  'Commit blocked to prevent commiting test focus. (do not commmit fdescribe, fcontext, or fit)'
        exit 1
    fi
done
exit
