#!/bin/sh
echo "Pre-commit hook to block focused tests"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

SAVEIFS=$IFS
IFS=$'\n'
for FILE in `git diff-index --diff-filter=AM --name-only $against`
do
    # Check if the file contains patterns
    if git grep --cached -q -e '^ *fdescribe' -e '^ *fcontext' -e '^ *fit' -- $FILE
    then
        echo $FILE  ': Commit blocked to prevent commiting test focus. (do not commit fdescribe, fcontext, or fit)'
	echo -e "\a"
        exit 1
    fi
done
IFS=$SAVEIFS
echo "Commit ok, no focused tests found in staged changes"
exit
